.\"-
.\" Manual page written by Timothy Brown <Timothy.P.Brown@noaa.org>
.\"
.\"
.Dd September 6, 2016
.Os
.Dt ACCOUNT_DU_USAGE 1 CON
.Sh NAME
.Nm account_du_usage
.Nd account disk usage notification email
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl A
.Op Fl a Ar acct
.Op Fl f
.Op Fl m
.Op Fl p Ar #
.Op Fl r
.Sh DESCRIPTION
.Nm
is a shell script to generate an email warning of account disk
usage. It uses
.Nm the generated quota files under
.B /home/admin/monitoring/quotas/reports/
to obtain the percentage of disk allocation used.
.Pp
The following options are available:
.Bl -tag -width flag
.It Fl h
Display a short help message and exit.
.It Fl A
Append the account to the end of the default accounts.
.It Fl a Ar acct
Check the usage of the account
.Ar acct
.It Fl f
Generate a full report, on lustre this is two deep.
.It Fl m
Email the report, instead of printing to stdout.
.It Fl p Ar #
Generate a report if the usage is greater that
.Ar #
percentage.
.It Fl r
Re-run the usage, even if a report has been generated this month.
.Sh EXAMPLES
The command:
.Pp
.Dl "account_du_usage"
.Pp
Will check the disk for all the projects you are a member of. While,
.Pp
.Dl "account_du_usage -p 75 -a dtc-hurr"
.Pp
will check the disk usage for the dtc-hurr project and report if it has
used more than 75% of the quota.
.Pp
An example of calling
.Nm
from a crontab would be:
.Dl "MAILTO=Timothy.P.Brown@noaa.gov"
.Dl "3 0 * * * "account_du_usage -f -m "
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr bash 1 ,
.Xr awk 1 ,
.Xr grep 1 ,
.Xr mail 1 ,
.Sh STANDARDS
The
.Nm
command is expected to be
.St -p1003.2
compatible.
.Sh AUTHOR
Written by Timothy Brown
.Sh BUGS
Report bugs to <Timothy.P.Brown@noaa.gov>
